[features]
seeds = false
[programs.localnet]
gm_solana = "HnqfyUBbMowVeuBAig8MctDh3VvV9yoFAkGs8VpLDJcV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/amman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
